sudo: false
language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules
    - ~/.npm
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run validate
  - npm run build
after_success:
  - npm run report-coverage
  - npm install -g travis-deploy-once
  - travis-deploy-once "npm run semantic-release"
  