name: Build, Test and Release
# This workflow will build, test and release our CLI

# we only run this workflow on the main (release) branch for both commits and PRs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # we start with the build job
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
        env:
            CI: true
  # Test
  # we release if everything is fine
  Release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}